### ISSUE TITLE
Enhancement: Allow RadialDistributionFunction to be defined by atom indices

### ISSUE THREAD

**Issue by bjmorgan** [materialsvirtuallab/pymatgen-diffusion#17]
At present the `RadialDistributionFunction` class is initialised using `species` and `reference_species` arguments, to select the atoms used in calculating the RDF. The species labels are used to generate index lists inside the `__init__` method: e.g.
```python
indices = [j for j, site in enumerate(structures[0])
                   if site.specie.symbol in species]
```

This would be more flexible if atoms could be selected directly by index. e.g.
```python
RadialDistributionFunction(spec_indices=[0, 1, 2, 3], ref_spec_indices=[4, 5, 6, 7])
```
as it would allow you to calculate RDFs for a subset of a particular species (e.g. Li only at specific sites in the lattice).

To allow this *and* selecting by species labels, I can think of two possible approaches:

1. Add new optional arguments to the current `__init__` method, along with logic to allow defined indices to supersede the default species arguments.
This has the advantage of not changing the API for RDFs generated using species labels, at the cost of making the API and code more complex.

2. Change the `__init__` method to *only* accept selection by indices. Selection by species label is moved to a new class method e.g. `RadialDistributionFunction.from_species_labels('Li')` which contains the code to identify the correct indices, and then calls the class `__init__()` method. I think this keeps the code logic cleaner, but breaks backwards compatibility with the current API.

**Comment by shyuep** [comment]
I am fine with option 2. But my students (@adengz and @Zhuoying and @HanmeiTang) should comment whether they are fine with breaking the backward compatibility. It shouldn't be that big an issue since this is a specialized package used by a few groups.

**Comment by HanmeiTang** [comment]
I think option 2 is fine.

**Comment by HanmeiTang** [comment]
@bjmorgan Let us know if this works.

**Comment by bjmorgan** [comment]
Looks to be working as expected (@HanmeiTang thank you for the quick implementation, saving me the trouble).
