### ISSUE TITLE
User StructureGraph for DistinctPathFinder

### ISSUE THREAD

**Issue by jmmshn** [materialsvirtuallab/pymatgen-diffusion#19]
I'm trying to add the PR that was previously intended for pymatgen.
#https://github.com/materialsproject/pymatgen/pull/1435

My understanding of the current implementation of DistinctPathFinder is that it only looks for distinct paths and does not keep track of all paths.
My usage scenario requires the full list of hops (I'm planning on analyzing full migrations pathways using either charge density of IDPP).  This will require some redesign of the class.
If there are no objections, I would like to rewrite the DistinctPathFinder with the StructureGraph to keep track of all the symmetry equivalent hops.  I think I can keep the output as a list of MigrationPaths so it won't affect the rest of the codebase very much.

However, doing this means that we will have to compare any two hops to check if they are equivalent.  The only way I can see for doing this is by adding two dummy atoms at the endpoints for each hop and performing structure matching.
So I will have to replace how the set of symmetrically inequivalent hops are generated.

This is going to take some effort and I just wanted to make sure the devs agree with my approach before I start coding this up.  And make sure doing this will not disrupt other ongoing efforts.

Thanks in advance.

**Comment by jmmshn** [comment]
Additional comment:
Using the end-point comparing approach should also make enumerating the vacancy migration much more straight forward.
Assuming the input is a structure with all the sites occupied.
For the interstitial we will just structurematch an empty structure with two dummy atoms at two of the nodes in the structuregraph.
For the vacancy we still add two dummy atoms at the nodes of the structuregraph which are atomic sites.  Only difference is we add the working ion on all the other sites for the structurematcher fitting.

**Comment by shyuep** [comment]
Just to clarify - what do you mean by the PathFinder does not keep track of all paths?  You mean even symmetrically equivalent pathways? That can be generated simply by applying the symmetry operations of the spacegroup to all distinct paths.

The code already checks whether paths are equivalent. Just to clarify that the start and end points are INSUFFICIENT to denote whether a path is distinct. You need the endpoints and the midpoint of the pathway. I suggest you looking at the `MigrationPath.__eq__` method to understand how distinct paths are determined. I think this will work in your case as well.

Also, the current code works with vacancy migration. To make it work with an additional atom migration, all that needs to be done is to insert dummy atoms into the distinct sites and postprocess it.

I suggest you throw the code a few example structures with vacancy migration and see what it gives you first before making mods.

**Comment by jmmshn** [comment]
Thanks for the input!  I really helped clear things up.
> You mean even symmetrically equivalent pathways? That can be generated simply by applying the symmetry operations of the spacegroup to all distinct paths.
That was the additional part that I needed.  I will try to generate the full network of paths thisway and compare with the structureGraph results to convince myself.

> The code already checks whether paths are equivalent. BTW, just the start and end points alone are INSUFFICIENT
OK, agreed.  I think I have a better idea of what needs to be done now.
I will reach out if I have anymore questions

**Comment by jmmshn** [comment]
> The code already checks whether paths are equivalent. BTW, just the start and end points alone are INSUFFICIENT

**Comment by phillik** [comment]
Hi, I know this is closed, but i don't understand how to apply the symmetry operations of the group in practical scripting terms. I have the exact same issue as the original poster

**Comment by shyuep** [comment]
The code already does this automatically for you. So you do not need to apply the operations yourself. If you want to know how the operations are applied, you can look at the source code.
