### ISSUE TITLE
Occupancy analysis

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/pymatgen-diffusion#7]
Occupancy analysis based on AIMD simulations should be added.

**Comment by johnson1228** [comment]
@shyuep I have added a class for occupancy analysis. Will add an ipython notebook example soon.

**Comment by shyuep** [comment]
A few issues:

i. The -- attribute is not the right syntax for Sphinx doc.
ii. Indices is not a valid arg in __init__. 
iii. NCount is not pep8 style.
iv. As far as I can tell, this does not support NpT simulations?

For future reference, new features need to be implemented in a separate branch/fork and then a pull request submitted. That way, we can comment on the pull request first.

**Comment by johnson1228** [comment]
Thanks. I have corrected (i) to (iii). As for (iv), you are right that the current version only works for NVT ensemble. In the case of NpT simulations, defining the reference sites is a bit tricky since the cell parameters may change substantially before reaching equilibrium.
