### ISSUE TITLE
add checking percolating function in neb/pathfinder

### ISSUE THREAD

**Issue by Zhuoying** [materialsvirtuallab/pymatgen-diffusion#8]
For some complicated alkali conductors, the default 5 Angstrom max_path_length will lead to quite many paths and may be more than needed. If we reduce the path length cutoff and can still form the percolating pathways, it would help to either save efforts in unnecessary NEB calculations or quick estimate if a material is a 3D conductor before doing any calculations.

**Comment by shyuep** [comment]
Go ahead. I would suggest implementing an *intelligent* algorithm to ascertain the percolating pathway and the min distance. In fact, it does not even have to be a min distance applied to all sites. Some sites are indeed further away than others. I would actually suggest considering the first NN, followed by next NN, etc., whatever that distance may be. The distance_matrix in the structure object can help.

**Comment by Zhuoying** [comment]
Pull request merged.
